function trstr = utils_tr_thead
    nl = [char(13),newline];
    idt2 = [char(9),char(9)]; idt3 = [char(9),char(9),char(9)];
    msign = '&#8863;'; psign = '&#8862;';
    button_tag = ['<button onclick="hide_show_table_colume(this)">',msign,'</button>'];
    buttonp_tag = ['<button onclick="hide_show_table_colume(this)">',psign,'</button>'];
    th_secname = [idt3,'<th title="section name"> section </th>',nl];
    th_userDecision = [idt3,'<th title="section status"><span class="ud">status </span>',...
        button_tag,'</th>',nl];
    th_batchTimestamp = [idt3,'<th title="timestamp in batch folder name"><span class="bts">batch timestamp </span>',...
        button_tag,'</th>',nl];
    th_mfovNum = [idt3,'<th title="number of mFoVs in the section"><span class="mnb">mFoV # </span>',...
        button_tag,'</th>',nl];
    th_fspNum = [idt3,'<th title="number of focus support points"><span class="fsp">FSP # </span>',...
        button_tag,'</th>',nl];
    th_duration = [idt3,'<th title="microscope time cost of the section"><span class="drt">duration </span>',...
        button_tag,'</th>',nl];
    th_fullresImg = [idt3,'<th title="mFoVs with missing or duplicated full-res images"><span class="fri">full-res imgs </span>',...
        button_tag,'</th>',nl];
    th_thumbImg = [idt3,'<th title="mFoVs with missing or duplicated thumbnail images"><span class="tni">thumb imgs </span>',...
        button_tag,'</th>',nl];
    th_fullresCoord = [idt3,'<th title="mFoVs with missing full-res coordinates"><span class="frc">full-res coord </span>',...
        button_tag,'</th>',nl];
    th_thumbCoord = [idt3,'<th title="mFoVs with missing thumbnail coordinates"><span class="tnc">thum coord </span>',...
        button_tag,'</th>',nl];
    th_regionmetadata = [idt3,'<th title="status of region_metadata.csv"><span class="rmd">metadata </span>',...
        button_tag,'</th>',nl];
    th_focusmap = [idt3,'<th title="status of FocusMap.txt"><span class="fm">focus map </span>',...
        button_tag,'</th>',nl];
    th_protocol = [idt3,'<th title="status of protocol.txt"><span class="prt">protocol </span>',...
        button_tag,'</th>',nl];
    th_workflow = [idt3,'<th title="status of workflow.xaml"><span class="wf">workflow </span>',...
        buttonp_tag,'</th>',nl];
    th_roi = [idt3,'<th title="rotation angle of ROI"><span class="roi">ROI align </span>',...
        button_tag,'</th>',nl];
    th_sfovStitch = [idt3,'<th title="rotation angle of mFoV"><span class="sfvst">sFoV stitch </span>',...
        button_tag,'</th>',nl];
    th_mfovStitch = [idt3,'<th title="mFoV overlap gaps and low-confs"><span class="mfvst">mFoV stitch </span>',...
        button_tag,'</th>',nl];
    th_jitter = [idt3,'<th title="number of mFoVs with jitter at the top"><span class="jt">jitter </span>',...
        button_tag,'</th>',nl];
    th_skew = [idt3,'<th title="number of mFoVs with skew at the top"><span class="skw">skew </span>',...
        button_tag,'</th>',nl];
    th_scanfault = [idt3,'<th title="number of mFoVs with scanfault"><span class="scf">scanfault </span>',...
        button_tag,'</th>',nl];
    th_IMQA = [idt3,'<th title="image quality values"><span class="imqa">IMQA </span>',...
        button_tag,'</th>',nl];
    th_worstBeams = [idt3,'<th title="beam numbers with worst image quality scores"><span class="wstb">worst beams </span>',...
        button_tag,'</th>',nl];
    th_userComments = [idt3,'<th title="comments by the user"><span class="uc">user comments </span>',...
        button_tag,'</th>',nl];
    th_sectionID = [idt3,'<th class="secid">UUID</th>',nl];

    trstr = [idt2,'<tr>',nl,...
    th_secname,...
    th_userDecision,...
    th_batchTimestamp,...
    th_mfovNum,...
    th_fspNum,...
    th_duration,...
    th_fullresImg,...
    th_thumbImg,...
    th_fullresCoord,...
    th_thumbCoord,...
    th_regionmetadata,...
    th_focusmap,...
    th_protocol,...
    th_workflow,...
    th_sfovStitch,...
    th_mfovStitch,...
    th_jitter,...
    th_skew,...
    th_scanfault,...
    th_roi,...
    th_IMQA,...
    th_worstBeams,...
    th_userComments,...
    th_sectionID,...
    idt2,'</tr>',nl];
end